# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sarra Bouhenni
title: Realtime ML researcher
email: sarra.bouhenni@gmail.com
address: Bordeaux, Nouvelle Aquitaine, France

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: SarraBouhenni
github_username:  sarra-bouhenni
stackoverflow_username: "3980759"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: sarrabouhenni
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-1091-3909

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-min.jpg
about_content: | # this will include new lines to allow paragraphs
  I enjoy building fast, efficient and scalable algorithms for big graphs and big data in general. 
  I hold a PhD in data science that involved the design of distributed algorithms of graph pattern matching on current Think-Like-A-Vertex graph processing systems.
  I am most skilled in: <mark>Spark</mark> and <mark>Scala</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ubiquity.AI
        link: https://ubiquity.ai
        # link_text: boringcompany.com
        sub_title: Realtime ML researcher
        caption: July 2022 - Present
        #quote: >
        #  I work on distributed algorithms of big graphs and big data processing platforms
        description: | # this will include new lines to allow paragraphs
            I work on designing large scale parallel and distributed machine learning algorithms for streaming data.
            
            Ubiquity.AI helps Ad Networks to increase their ROI by removing ad decisioning bottlenecks thanks to a proprietary Decision as a Service platform that increases their margin up to 300% while preserving the scale.
            Unlike solutions that rely on constant manual tuning or general-purpose Machine Learning not fitted for all KPIs, Ubiquity.AI empowers Ad Networks to grow their margin and customer base without growing their operational costs.
      - layout: left
        title: CERIST Research Center
        link: www.cerist.dz
        # link_text: boringcompany.com
        sub_title: Research Associate
        caption: Februaury 2022 - June 2022
        #quote: >
        #  I work on distributed algorithms of big graphs and big data processing platforms
        description: | # this will include new lines to allow paragraphs
            I worked on distributed algorithms of big graphs and big data processing platforms.
            
            My research interests include: Distributed algorithms, Graph algorithms, Graph Pattern Matching, ML Applied to graphs, graph data models. 
      - layout: left
        title: CERIST Research Center
        link: www.cerist.dz
        # link_text: boringcompany.com
        sub_title: Graduate Teaching Assistant
        caption: June 2019 - March 2021
        #quote: >
        #  I work on distributed algorithms of big graphs and big data processing platforms
        description: | # this will include new lines to allow paragraphs
            I delivered the programming course `Big Data - Scala` in the post-graduation training PGS. It covers: basic syntax of Scala programming language, functional programming with Scala, and Scala collections.
            
            I also delivered the introductory course `Frameworks for big graphs - GraphX`.
            
      - layout: left
        title: Yassir
        link: yassir.com
        # link_text: boringcompany.com
        sub_title: Data Science Consultant
        caption: August 2017 - December 2017
        #quote: >
        #  I work on distributed algorithms of big graphs and big data processing platforms
        description: | # this will include new lines to allow paragraphs
            I worked on improving the logging system of the VTC application Yassir. My responsitibilies included mainly:
            - Extraction of the log events available at a Kafka server using a logger implemented with NodeJs.
            - Transformation of the events to compresenhive information to be stored on an Elasticsearch server.
            - Creation of dashboards for the visualization and reporting of logs using Kibana.
      - layout: left
        title: AITECH
        link: ai-technologies.co
        # link_text: boringcompany.com
        sub_title: Data Science Intern
        caption: September 2016 - June 2017
        #quote: >
        #  I work on distributed algorithms of big graphs and big data processing platforms
        description: | # this will include new lines to allow paragraphs
            In my final year's engineering project, I worked on the design and development of a monitoring system for predicting plant diseases in Algeria, using Incremental Machine Learning algorithms. My responsibilities in this project included:
            - Collecting data on plant disease prediction for the two diseases Fusarium Head Blight and Potato Mildiew.
            - Design of a new algorithm for plant disease prediction based on incremental learning.
            - Design and development of a backend for disease prediction based on current weather conditions, using Python and Django.
            - Design and development of a web application, using Angular, for monitoring and visualization of the disease spread across Algerian crops.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Université Claude Bernard - Lyon 1 and Ecole Supérieure d'Informatique - Alger
        caption: 2018 - 2021
        sub_title: Joint PhD in Computer Science
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I worked in my PhD on the problem of Graph Pattern Matching (GPM) in the context of large-scale distributed graphs. 
          PhD Thesis dissertation can be downloaded via this link: [Parallel and Distributed Algorithms for Pattern Matching in Big Graphs](https://www.researchgate.net/publication/358743592_Parallel_and_Distributed_Algorithms_for_Pattern_Matching_in_Big_Graphs)
      - layout: left
        title: Ecole Supérieure d'Informatique 
        caption: 2012 - 2017 
        sub_title: Engineering degree in IT Systems
        description: |
          My final year's project was about the development of a plant disease forecasting platform.
          Thesis dissertation can be downloaded via this link: [APDM : vers une plateforme intelligente pour la prevision des maladies végétales](https://drive.google.com/file/d/1QmuhPy8RzpltF8gWpgLG8hjICcmnCM4R/view)

  - title: Technical Experience
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Programming Languages**
          * **Java:** I work with Java on a daily basis.
          * **Scala:** I have an experience of 5 years working with Scala and functional programming. I have implemented several distributed and parallel algorithms of graphs with Scala, Spark RDDs and GraphX.
          * **Python:** I had the chance to work with Python for one year during my final year’s engineering project. I have implemented different data science algorithms in addition to a web application using Django. I have also worked on a data science project using Python during my experience at Ya Technologies.
          * Basic knowledge of C, C++

      - **Big data plateforms**
          * **Spark Apache:** I have an experience of 4 years working with Spark and its module GraphX for designing graph pattern matching algorithms in the context of massive graphs. I am also responsible of the deployment and management of the big data plateform at the CERIST research center.
          * **Elastic Stack:** I have worked with the different components of the Elastic Stack including Logstash, Elasticsearch and Kibana during my experience as a data science consultant at Yassir. I have also an experience in the deployment and management of an Elasticsearch cluster on a production environment using Docker and Kubernetes.
  - title: Spoken Languages 
    layout: text
    content: |
      Arabic (native speaker) -- French  -- English
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
